<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/09/09 10:47:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=frontend',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
